import assert from 'node:assert/strict';
import {build} from 'esbuild';
const result=await build({entryPoints:['src/utils/backup.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const api=await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
globalThis.window={dispatchEvent:()=>{}};globalThis.CustomEvent=class {};
const session={id:'test-1',title:'테스트',date:'2026-09-09',startTime:'2026-09-09T00:00:00Z',durationSeconds:60,completed:true,exercises:[{id:'ex-1',exerciseId:'viking_press_machine',equipmentType:'machine',sets:[{id:'set-1',setNumber:1,weight:40,reps:10,completed:true}]}]};
const backup={format:'iron-muscle-backup',version:1,exportedAt:'2026-09-10',sessions:[session],customExercises:[],activeSession:null};
assert.equal(api.restoreBackup(backup).added,1);
assert.equal(api.restoreBackup(backup).skipped,1);
assert.equal(api.createBackup().sessions.length,1);
const other=structuredClone(backup);other.sessions[0].id='test-2';
assert.equal(api.restoreBackup(other).sessions.length,2);
const invalid=structuredClone(backup);invalid.sessions[0].exercises[0].sets[0].weight=-5;
assert.throws(()=>api.parseBackup(JSON.stringify(invalid)));
assert.throws(()=>api.parseBackup('{}'));
const before=[...memory.entries()];let writes=0;const original=localStorage.setItem;
localStorage.setItem=(k,v)=>{if(++writes===2)throw new Error('Quota');return original(k,v);};
assert.throws(()=>api.restoreBackup({...backup,sessions:[{...session,id:'test-3'}]}));
assert.deepEqual([...memory.entries()],before);
console.log('PASS: backup round trip, merge, duplicates, validation, rollback on storage failure');
